export const schema = {
  type: "object",
  properties: {
    header: {
      type: "object",
      "x-component": "Header",
      default: {
        processName: "蜂享家双倍佣金审核",
        processStatus: 1,
      },
    },
    directionalRuleStr: {
      "x-component": "Input",
      component_key: "directionalRuleStr",
      type: "string",
      editable: false,
      sort: 6,
      title: "定向补贴规则",
      required: false,
      default: "",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 14,
      placeholder: "",
      "x-display": false,
      "x-visible": false,
      "x-decorator": "FormItem",
      "x-component-props": {
        style: "padding: 100px;",
      },
    },
    activityEndTime: {
      "x-component": "DatePicker",
      component_key: "activityEndTime",
      type: "string",
      editable: false,
      sort: 3,
      title: "活动结束时间",
      required: false,
      default: "2022-05-27T16:00:00.000Z",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 11,
      placeholder: "",
      "x-component-props": { type: "datetime", format: "yyyy-MM-dd HH:mm:ss" },
      "x-decorator": "FormItem",
    },
    directionalPayer: {
      "x-component": "Input",
      component_key: "directionalPayer",
      type: "string",
      editable: false,
      sort: 7,
      title: "定向补贴承担方",
      required: false,
      default: "",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 15,
      placeholder: "",
      "x-display": false,
      "x-visible": false,
      "x-decorator": "FormItem",
    },
    activityName: {
      "x-component": "Input",
      component_key: "activityName",
      type: "string",
      editable: false,
      sort: 1,
      title: "活动名称",
      required: false,
      default: "100393614",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 9,
      placeholder: "",
      "x-decorator": "FormItem",
    },
    activityScope: {
      "x-component": "Input",
      component_key: "activityScope",
      type: "string",
      editable: false,
      sort: 8,
      title: "活动范围",
      required: false,
      default: "商品级别，商品id：100393614",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 16,
      placeholder: "",
      "x-decorator": "FormItem",
    },
    activityStartTime: {
      "x-component": "DatePicker",
      component_key: "activityStartTime",
      type: "string",
      editable: false,
      sort: 2,
      title: "活动开始时间",
      required: false,
      default: "2022-04-28T08:46:00.000Z",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 10,
      placeholder: "",
      "x-component-props": { type: "datetime", format: "yyyy-MM-dd HH:mm:ss" },
      "x-decorator": "FormItem",
    },
    normalRuleStr: {
      "x-component": "Input",
      component_key: "normalRuleStr",
      type: "string",
      editable: false,
      sort: 4,
      title: "通用补贴规则",
      required: false,
      default: "销售佣金翻倍，增加1.0倍",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 12,
      placeholder: "",
      "x-decorator": "FormItem",
    },
    gmtCreate: {
      "x-component": "DatePicker",
      component_key: "gmtCreate",
      type: "string",
      editable: false,
      sort: 10,
      title: "创建时间",
      required: false,
      default: "2022-04-28T08:45:12.000Z",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 18,
      placeholder: "",
      "x-component-props": { type: "datetime", format: "yyyy-MM-dd HH:mm:ss" },
      "x-decorator": "FormItem",
    },
    normalPayer: {
      "x-component": "Input",
      component_key: "normalPayer",
      type: "string",
      editable: false,
      sort: 5,
      title: "通用补贴承担方",
      required: false,
      default: "平台",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 13,
      placeholder: "",
      "x-decorator": "FormItem",
    },
    operator: {
      "x-component": "Input",
      component_key: "operator",
      type: "string",
      editable: false,
      sort: 9,
      title: "设置人",
      required: true,
      default: "暖暖",
      "x-rules": "",
      enum: [],
      "x-reactions": "",
      id: 17,
      placeholder: "",
      "x-decorator": "FormItem",
    },
    upload: {
      type: 'array',
      title: '上传',
      default: [
        'assets/img/2020/04/03/n_1585902143588_7571___size800x800.jpg',
        'assets/img/2020/04/03/n_1585902143594_4372___size800x800.jpg',
        'assets/img/2020/04/03/n_1585902143651_1989___size800x800.jpg',
        'assets/img/2020/04/03/n_1585902158075_2331___size750x272.png',
        'assets/img/2020/04/03/n_1585902158126_5951___size750x272.jpg',
      ],
      'x-decorator': 'FormItem',
      'x-component': 'ImageUpload',
      required: true,
    },
    flow: {
      type: "array",
      "x-component": "Flow",
      default: [
        {
          processDate: '2022-04-28T08:45:12.000Z',
          audiGroupMemberList: [
            { userName: "拳头", userId: 39707363 },
            { userName: "净源", userId: 70931791 },
            { userName: "礼荇", userId: 222224298727 },
          ],
          nodeDesc: "审核活动",
          sort: 0,
          id: 460,
          status: false,
        },
        {
          processDate: '2022-04-28T08:45:12.000Z',
          audiGroupMemberList: [
            { userName: "拳头", userId: 39707363 },
          ],
          nodeDesc: "发布活动",
          sort: 1,
          id: 459,
          status: false,
        },
      ],
    },
    submit: {
      type: 'void',
      "x-component": "Operator",
    }
  }
};
